BEGIN;

ALTER TABLE IF EXISTS "user" DROP COLUMN IF EXISTS "uid";

ALTER TABLE IF EXISTS "user"
  ADD COLUMN IF NOT EXISTS "favoriteEateries" TEXT[] NOT NULL DEFAULT '{}'::TEXT[];

ALTER TABLE IF EXISTS "user"
  ADD COLUMN IF NOT EXISTS "cooperationIds" TEXT[] NOT NULL DEFAULT '{}'::TEXT[];

ALTER TABLE IF EXISTS "user"
  ADD COLUMN IF NOT EXISTS "travelExp" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE IF EXISTS "user"
  ALTER COLUMN "avatarUrl" DROP NOT NULL;

ALTER TABLE IF EXISTS "user"
  ALTER COLUMN "userTier" SET DEFAULT 'dong';

CREATE TABLE IF NOT EXISTS categories (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL UNIQUE,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS eateries (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  province VARCHAR(255) NOT NULL,
  address VARCHAR(255) NOT NULL,
  description TEXT,
  phone VARCHAR(32),
  "imageUrl" TEXT,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS eateries_province_idx ON eateries (province);

COMMIT;
